name: database
on:
  push:
    branches: [ mainline ] # Trigger workflow on git push to main branch
  workflow_dispatch: # Allow manual invocation of the workflow
jobs:
  ci:
    runs-on: ubuntu-latest
  
    services:
      mysql-master:
        image: mysql:8.0
        ports:
          - 3306/tcp
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_HOST: ${{ env.MYSQL_HOST }}
        options: >-
          --name=mysql-master
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
          - uses: actions/checkout@v2
          - name: Install packages
            run: "npm ci"
          - name: Setup Database
            run: "npm run Migrations/Scripts"
          - name: Run Tests
            run: "npm run test"
